const developerMarkup = `<section class="developer-section" id="developer"><div class="developer-mark" aria-hidden="true"><span>F</span><i></i><i></i></div><div class="developer-copy"><p class="eyebrow">THE PERSON BEHIND FRAMEOS</p><h2>Built by <em>Adarsh Viswam.</em></h2><p class="developer-role">AI Solutions Architect</p><p class="muted">FrameOS is shaped in the open. Have an improvement, a feature idea, or a bug to report? Send a note and help make the next cut better.</p><a class="developer-email" href="mailto:adarshmanjady@gmail.com">adarshmanjady@gmail.com <span>↗</span></a></div></section>`;

export function withDeveloperSection(html: string): string {
  const linkedin = `<a class="developer-linkedin" href="https://www.linkedin.com/in/adarsh-viswam-95161016b/" target="_blank" rel="noreferrer">LinkedIn profile <span>↗</span></a>`;
  return html.replace("</main>", `${developerMarkup.replace("</div></section>", `${linkedin}</div></section>`)}</main>`);
}

export const developerCss = String.raw`
.developer-section{max-width:1240px;margin:auto;padding:86px 5%;display:grid;grid-template-columns:220px 1fr;gap:70px;align-items:center;border-bottom:1px solid var(--line);background:radial-gradient(circle at 10% 50%,#2e6d681c,transparent 42%)}.developer-mark{width:170px;height:170px;position:relative;display:grid;place-items:center;transform:rotate(-7deg)}.developer-mark:before{content:'';position:absolute;inset:8px;border:1px solid #9ce6ce66;border-radius:28px;background:linear-gradient(145deg,#2e6d6844,#1c1c2300);box-shadow:18px 18px 0 #9b83d41a,0 20px 40px #0005}.developer-mark span{position:relative;z-index:1;background:var(--accent);color:#211638;border-radius:12px;padding:10px 18px;font-size:42px;font-weight:700;letter-spacing:-4px;box-shadow:5px 5px 0 #7e699f55}.developer-mark i{position:absolute;width:8px;height:8px;border-radius:50%;background:#9ce6ce;right:4px;top:23px;box-shadow:-133px 107px 0 #b5a1ff}.developer-mark i:last-child{width:5px;height:5px;right:32px;top:150px;background:#b5a1ff}.developer-copy{max-width:650px}.developer-copy h2{margin-bottom:8px}.developer-role{color:#9ce6ce;font:11px Consolas,monospace;letter-spacing:1.6px;text-transform:uppercase;margin-bottom:18px}.developer-copy .muted{max-width:570px;font-size:14px;margin-bottom:22px}.developer-email{display:inline-flex;align-items:center;gap:12px;color:var(--accent);font:13px Consolas,monospace;border-bottom:1px solid #b5a1ff66;padding-bottom:7px;transition:color .2s,border-color .2s,transform .2s}.developer-email span{font-size:18px}.developer-email:hover{color:#e1d7ff;border-color:#e1d7ff;transform:translateX(3px)}@media(max-width:760px){.developer-section{grid-template-columns:1fr;gap:28px;padding:65px 6%}.developer-mark{width:120px;height:120px}.developer-mark span{font-size:31px;padding:8px 14px}.developer-mark:before{border-radius:22px}}
`;

export const developerLinkedinCss = String.raw`.developer-linkedin{display:inline-flex;align-items:center;gap:10px;margin-left:22px;color:#9ce6ce;font:11px Consolas,monospace;border-bottom:1px solid #9ce6ce66;padding-bottom:7px;transition:color .2s,border-color .2s,transform .2s}.developer-linkedin span{font-size:16px}.developer-linkedin:hover{color:#e1fff5;border-color:#e1fff5;transform:translateX(3px)}@media(max-width:760px){.developer-linkedin{margin:18px 0 0;display:flex;width:max-content}}`;
