/** Browser monitoring only. Native rendering remains authoritative for DSP. */
export const audioPreviewJavaScript = String.raw`
let audioContext;
const audioPlayers=new Map();
function startAudioContext(){audioContext ||= new AudioContext();return audioContext.resume();}
function stopAudioPreview(clear=false){for(const entry of audioPlayers.values()){entry.media?.pause();if(clear){entry.nodes?.forEach(n=>n.disconnect());entry.media?.removeAttribute('src');entry.media?.load();}}if(clear)audioPlayers.clear();}
function fadeAmount(curve,x){x=Math.max(0,Math.min(1,x));if(curve==='equal_power')return Math.sin(x*Math.PI/2);if(curve==='s_curve')return x*x*(3-2*x);if(curve==='logarithmic')return Math.log10(1+9*x);return x;}
function audioLevel(item,at){let level=Math.pow(10,(item.audio.gainDb||0)/20);const local=at-seconds(item.timelineRange.start),length=seconds(item.timelineRange.duration);for(const effect of item.effects||[]){if(!effect.enabled||effect.capabilityId!=='frameos.audio.channel-strip')continue;for(const fade of effect.parameters.fades||[]){const d=seconds(fade.duration);level*=fadeAmount(fade.curve,(fade.kind==='in'?local:length-local)/d);}const duck=effect.parameters.timelineDuck;if(duck){const envelope=Math.min(1,Math.max(0,(local-duck.start)/duck.attack))*Math.min(1,Math.max(0,(duck.end+duck.release-local)/duck.release));level*=Math.pow(10,-duck.reductionDb*envelope/20);}}return level;}
function buildAudioGraph(entry,item){const key=JSON.stringify([item.audio,item.effects]);if(entry.key===key)return;entry.nodes.forEach(n=>n.disconnect());entry.nodes=[entry.source];let tail=entry.source;const connect=node=>{tail.connect(node);entry.nodes.push(node);tail=node;};for(const effect of item.effects||[]){if(!effect.enabled||effect.capabilityId!=='frameos.audio.channel-strip')continue;const p=effect.parameters;for(const band of p.eq?.bands||[]){if(!band.enabled)continue;const filter=audioContext.createBiquadFilter();filter.type=({low_cut:'highpass',high_cut:'lowpass',low_shelf:'lowshelf',high_shelf:'highshelf',bell:'peaking'})[band.kind];filter.frequency.value=Math.min(audioContext.sampleRate/2-1,band.frequencyHz);filter.Q.value=band.q;filter.gain.value=band.gainDb;connect(filter);}if(p.compressor){const c=audioContext.createDynamicsCompressor(),v=p.compressor;c.threshold.value=Math.max(-100,v.thresholdDb);c.ratio.value=Math.min(20,v.ratio);c.attack.value=Math.min(1,v.attackMs/1000);c.release.value=Math.min(1,v.releaseMs/1000);c.knee.value=Math.min(40,v.kneeDb);connect(c);const makeup=audioContext.createGain();makeup.gain.value=Math.pow(10,(v.makeupGainDb||0)/20);connect(makeup);}if(p.limiter){const c=audioContext.createDynamicsCompressor();c.threshold.value=p.limiter.ceilingDb;c.ratio.value=20;c.knee.value=0;c.attack.value=.001;c.release.value=Math.min(1,p.limiter.releaseMs/1000);connect(c);}}
const pan=audioContext.createStereoPanner();pan.pan.value=item.audio.pan||0;connect(pan);entry.gain=audioContext.createGain();connect(entry.gain);tail.connect(audioContext.destination);entry.key=key;}
function syncAudioPreview(){if(!audioContext||state.sourceMode||!state.playing){stopAudioPreview();return;}const at=state.playhead,active=new Set();for(const track of seq()?.tracks||[]){if(!track.enabled||track.muted||!['audio','video'].includes(track.kind))continue;const crossfades=track.items.filter(i=>i.enabled&&i.type==='transition'&&i.capabilityId==='frameos.transition.audio_crossfade'&&at>=seconds(i.timelineRange.start)&&at<end(i));for(const item of track.items){if(item.type!=='clip'||!item.enabled||item.audio.muted)continue;const cross=crossfades.find(t=>t.fromItemId===item.id||t.toItemId===item.id);if(!cross&&(at<seconds(item.timelineRange.start)||at>=end(item)))continue;const asset=state.assets.find(a=>a.id===item.assetId);if(!asset||!['audio','video'].includes(asset.kind))continue;active.add(item.id);let entry=audioPlayers.get(item.id);if(!entry){entry={loading:true};audioPlayers.set(item.id,entry);const saved=entry;mediaUrl(asset).then(url=>{if(audioPlayers.get(item.id)!==saved)return;const media=document.createElement('audio');media.preload='auto';media.src=url;const source=audioContext.createMediaElementSource(media);Object.assign(saved,{media,source,nodes:[source],loading:false});media.onerror=()=>{saved.failed=true;toast('Audio preview could not decode '+asset.name);};}).catch(e=>{saved.failed=true;toast(e.message);});continue;}if(entry.loading||entry.failed||entry.media.readyState<1)continue;const rate=playbackRateAt(item,at);if(rate<=0||rate<.0625||rate>16){entry.media.pause();continue;}buildAudioGraph(entry,item);let level=audioLevel(item,at);if(cross){const amount=(at-seconds(cross.timelineRange.start))/seconds(cross.timelineRange.duration);level*=item.id===cross.fromItemId?1-amount:amount;}entry.gain.gain.setTargetAtTime(level,audioContext.currentTime,.01);entry.media.playbackRate=rate;const expected=Math.max(0,sourceAt(item,at));if(entry.media.readyState>=1&&Math.abs(entry.media.currentTime-expected)>.08)entry.media.currentTime=expected;if(entry.media.paused&&!entry.starting){entry.starting=true;entry.media.play().catch(e=>{entry.failed=true;toast('Audio playback failed: '+e.message);}).finally(()=>entry.starting=false);}}}for(const [id,entry] of audioPlayers)if(!active.has(id)){entry.media?.pause();entry.nodes?.forEach(n=>n.disconnect());entry.media?.removeAttribute('src');entry.media?.load();audioPlayers.delete(id);}}
`;
