import { z } from "zod";

export const capabilityKinds = [
  "producer",
  "consumer",
  "filter",
  "transition",
  "analyzer",
  "codec",
  "hardware",
  "interchange",
  "operation",
] as const;

export const capabilityDescriptorSchema = z
  .object({
    id: z.string().min(1).max(512),
    kind: z.enum(capabilityKinds),
    name: z.string().min(1).max(512),
    description: z.string().max(8_192),
    available: z.boolean(),
    baseline: z.boolean(),
    provider: z.string().min(1).max(256),
    providerVersion: z.string().max(128).optional(),
    license: z.string().max(128).optional(),
    reasonUnavailable: z.string().max(4_096).optional(),
    alternatives: z.array(z.string().max(512)),
    parameters: z.record(z.string(), z.unknown()).optional(),
    metadata: z.record(z.string(), z.unknown()),
  })
  .strict();

export type CapabilityDescriptor = z.infer<typeof capabilityDescriptorSchema>;

export type OperationMaturity =
  "implemented" | "service" | "contract" | "planned";

export interface OperationDescriptor {
  name: string;
  family: string;
  description: string;
  maturity: OperationMaturity;
  reversible: boolean;
  requiredCapabilities: string[];
  readSet: string[];
  writeSet: string[];
  expectedWarnings: string[];
}

const implementedOperations = new Set([
  "project.metadata.set",
  "project.metadata.replace",
  "project.settings.set",
  "asset.add",
  "asset.remove",
  "asset.relink",
  "asset.replace",
  "asset.metadata.set",
  "asset.license.set",
  "asset.offline.set",
  "asset.proxy.create",
  "asset.proxy.remove",
  "sequence.add",
  "sequence.remove",
  "sequence.format.set",
  "sequence.replace",
  "sequence.duplicate",
  "sequence.nest",
  "sequence.color_space.set",
  "sequence.audio_layout.set",
  "track.add",
  "track.remove",
  "track.update",
  "track.items.replace",
  "track.reorder",
  "track.lock",
  "track.unlock",
  "track.mute",
  "track.unmute",
  "track.enable",
  "track.disable",
  "track.sync_lock",
  "track.bus.assign",
  "track.effect.add",
  "track.effect.remove",
  "item.add",
  "item.delete",
  "item.replace",
  "gap.add",
  "gap.remove",
  "title.add",
  "title.update",
  "title.remove",
  "title.template.apply",
  "clip.move",
  "clip.trim",
  "clip.split",
  "clip.insert",
  "clip.overwrite",
  "clip.append",
  "clip.duplicate",
  "clip.replace",
  "clip.lift",
  "clip.extract",
  "clip.ripple_delete",
  "clip.roll",
  "clip.slip",
  "clip.slide",
  "clip.link",
  "clip.unlink",
  "clip.freeze_frame",
  "clip.reverse",
  "clip.speed.set",
  "clip.speed_ramp.set",
  "clip.snap",
  "clip.reorder",
  "clip.group",
  "clip.ungroup",
  "item.transform.set",
  "video.position.set",
  "video.anchor.set",
  "video.scale.set",
  "video.crop.set",
  "video.rotation.set",
  "video.opacity.set",
  "video.blend_mode.set",
  "video.picture_in_picture.apply",
  "transition.add",
  "transition.remove",
  "transition.duration.set",
  "transition.parameter.set",
  "transition.keyframe.add",
  "transition.keyframe.remove",
  "effect.add",
  "effect.remove",
  "effect.parameter.set",
  "effect.enable",
  "effect.disable",
  "effect.reorder",
  "effect.range.set",
  "effect.preset.apply",
  "keyframe.add",
  "keyframe.remove",
  "keyframe.move",
  "keyframe.value.set",
  "keyframe.interpolation.set",
  "mask.add",
  "mask.remove",
  "mask.path.set",
  "mask.feather.set",
  "mask.invert.set",
  "mask.track.attach",
  "effect.mask.attach",
  "effect.mask.detach",
  "video.track_object",
  "tracked_object.remove",
  "multicam.create",
  "multicam.remove",
  "multicam.replace",
  "multicam.angle.switch",
  "multicam.sync",
  "color.exposure.set",
  "color.contrast.set",
  "color.saturation.set",
  "color.white_balance.set",
  "color.curves.set",
  "color.lift_gamma_gain.set",
  "color.lut.apply",
  "color.lut.remove",
  "color.space.set",
  "color.hdr_metadata.set",
  "color.ocio_transform.set",
  "audio.gain.set",
  "audio.pan.set",
  "audio.channel_map.set",
  "audio.fade.add",
  "audio.fade.remove",
  "audio.normalize",
  "audio.eq.set",
  "audio.compress",
  "audio.limit",
  "audio.denoise",
  "audio.duck",
  "audio.enhance_voice",
  "audio.bus.add",
  "audio.bus.remove",
  "audio.bus.route",
  "marker.add",
  "marker.remove",
  "marker.update",
  "marker.move",
  "caption.track.add",
  "caption.track.remove",
  "caption.style.set",
  "caption.cue.add",
  "caption.cue.update",
  "caption.cue.remove",
  "analysis.attach",
  "analysis.remove",
  "render.profile.add",
  "render.profile.update",
  "render.profile.remove",
]);

const implementedServiceOperations = new Set([
  "caption.import",
  "caption.export",
  "preview.frame",
  "preview.region",
  "preview.contact_sheet",
  "preview.waveform",
  "asset.thumbnail.create",
  "render.start",
  "render.cancel",
  "interchange.otio.import",
  "interchange.otio.export",
  "semantic.find_speaker",
  "semantic.find_quote",
  "semantic.find_scene",
  "semantic.find_object",
  "semantic.find_silence",
  "semantic.find_best_take",
  "semantic.remove_silences",
  "semantic.make_vertical",
  "semantic.match_cuts_to_music",
  "semantic.add_dynamic_captions",
]);

const operationFamilies: Record<string, string[]> = {
  project: [
    "project.metadata.set",
    "project.metadata.replace",
    "project.settings.set",
    "project.checkpoint.create",
    "project.branch.create",
    "project.branch.merge",
    "project.undo",
    "project.redo",
    "project.relink_all",
    "project.consolidate",
  ],
  asset: [
    "asset.add",
    "asset.remove",
    "asset.relink",
    "asset.proxy.create",
    "asset.proxy.remove",
    "asset.transcode",
    "asset.thumbnail.create",
    "asset.waveform.create",
    "asset.contact_sheet.create",
    "asset.metadata.set",
    "asset.license.set",
    "asset.sequence.detect",
    "asset.offline.set",
    "asset.replace",
  ],
  sequence: [
    "sequence.add",
    "sequence.remove",
    "sequence.format.set",
    "sequence.replace",
    "sequence.duplicate",
    "sequence.nest",
    "sequence.flatten",
    "sequence.duration.set",
    "sequence.color_space.set",
    "sequence.audio_layout.set",
  ],
  track: [
    "track.add",
    "track.remove",
    "track.update",
    "track.items.replace",
    "track.reorder",
    "track.lock",
    "track.unlock",
    "track.mute",
    "track.unmute",
    "track.enable",
    "track.disable",
    "track.sync_lock",
    "track.bus.assign",
    "track.effect.add",
    "track.effect.remove",
  ],
  editorial: [
    "item.add",
    "item.delete",
    "item.replace",
    "clip.insert",
    "clip.overwrite",
    "clip.append",
    "clip.move",
    "clip.trim",
    "clip.split",
    "clip.duplicate",
    "clip.replace",
    "clip.lift",
    "clip.extract",
    "clip.ripple_delete",
    "clip.roll",
    "clip.slip",
    "clip.slide",
    "clip.reorder",
    "clip.group",
    "clip.ungroup",
    "clip.link",
    "clip.unlink",
    "clip.freeze_frame",
    "clip.reverse",
    "clip.speed.set",
    "clip.speed_ramp.set",
    "clip.source_patch.set",
    "clip.record_patch.set",
    "clip.snap",
    "gap.add",
    "gap.remove",
    "compound.create",
    "compound.flatten",
    "multicam.create",
    "multicam.remove",
    "multicam.replace",
    "multicam.angle.switch",
    "multicam.sync",
  ],
  transform: [
    "item.transform.set",
    "video.position.set",
    "video.anchor.set",
    "video.scale.set",
    "video.crop.set",
    "video.rotation.set",
    "video.opacity.set",
    "video.blend_mode.set",
    "video.picture_in_picture.apply",
    "video.alpha_matte.set",
    "video.background_replace",
    "video.stabilize",
    "video.track_object",
    "tracked_object.remove",
  ],
  transition: [
    "transition.add",
    "transition.remove",
    "transition.duration.set",
    "transition.parameter.set",
    "transition.keyframe.add",
    "transition.keyframe.remove",
  ],
  effects: [
    "effect.add",
    "effect.remove",
    "effect.enable",
    "effect.disable",
    "effect.reorder",
    "effect.parameter.set",
    "effect.preset.apply",
    "effect.range.set",
    "effect.mask.attach",
    "effect.mask.detach",
    "keyframe.add",
    "keyframe.remove",
    "keyframe.move",
    "keyframe.value.set",
    "keyframe.interpolation.set",
    "mask.add",
    "mask.remove",
    "mask.path.set",
    "mask.feather.set",
    "mask.invert.set",
    "mask.track.attach",
  ],
  color: [
    "color.exposure.set",
    "color.contrast.set",
    "color.saturation.set",
    "color.white_balance.set",
    "color.curves.set",
    "color.lift_gamma_gain.set",
    "color.lut.apply",
    "color.lut.remove",
    "color.space.set",
    "color.hdr_metadata.set",
    "color.ocio_transform.set",
    "color.match_shots",
  ],
  audio: [
    "audio.gain.set",
    "audio.pan.set",
    "audio.fade.add",
    "audio.fade.remove",
    "audio.channel_map.set",
    "audio.bus.add",
    "audio.bus.remove",
    "audio.bus.route",
    "audio.normalize",
    "audio.eq.set",
    "audio.compress",
    "audio.limit",
    "audio.denoise",
    "audio.duck",
    "audio.remove_silence",
    "audio.sync",
    "audio.beats.detect",
    "audio.onsets.detect",
    "audio.enhance_voice",
  ],
  captions: [
    "caption.track.add",
    "caption.track.remove",
    "caption.cue.add",
    "caption.cue.update",
    "caption.cue.remove",
    "caption.import",
    "caption.export",
    "caption.transcribe",
    "caption.align",
    "caption.style.set",
    "caption.animate",
    "caption.highlight_words",
    "caption.safe_area.fit",
    "title.add",
    "title.update",
    "title.remove",
    "title.template.apply",
  ],
  markers: ["marker.add", "marker.remove", "marker.update", "marker.move"],
  analysis: [
    "analysis.transcribe",
    "analysis.language.detect",
    "analysis.speakers.diarize",
    "analysis.silence.detect",
    "analysis.scenes.detect",
    "analysis.shots.detect",
    "analysis.faces.detect",
    "analysis.objects.detect",
    "analysis.ocr",
    "analysis.motion.detect",
    "analysis.quality.score",
    "analysis.duplicates.detect",
    "analysis.music.classify",
    "analysis.embeddings.create",
    "analysis.search",
    "analysis.attach",
    "analysis.remove",
  ],
  semantic: [
    "semantic.find_speaker",
    "semantic.find_quote",
    "semantic.find_scene",
    "semantic.find_object",
    "semantic.find_silence",
    "semantic.find_best_take",
    "semantic.remove_silences",
    "semantic.sync_broll",
    "semantic.make_vertical",
    "semantic.add_dynamic_captions",
    "semantic.create_highlight",
    "semantic.create_short",
    "semantic.create_trailer",
    "semantic.match_cuts_to_music",
    "semantic.improve_pacing",
  ],
  render: [
    "preview.frame",
    "preview.region",
    "preview.contact_sheet",
    "preview.waveform",
    "render.start",
    "render.cancel",
    "render.retry",
    "render.image_sequence",
    "render.audio_only",
    "render.profile.add",
    "render.profile.update",
    "render.profile.remove",
  ],
  interchange: [
    "interchange.otio.import",
    "interchange.otio.export",
    "interchange.kdenlive.import",
    "interchange.kdenlive.export",
    "interchange.fcpxml.import",
    "interchange.fcpxml.export",
    "interchange.aaf.import",
    "interchange.aaf.export",
    "interchange.edl.import",
    "interchange.edl.export",
  ],
};

function humanize(name: string): string {
  return name.replaceAll(".", " ").replaceAll("_", " ");
}

const resourceTemplates: Record<string, string> = {
  project: "project",
  asset: "assets/{targetId}",
  sequence: "sequences/{sequenceId}",
  track: "sequences/{sequenceId}/tracks/{trackId}",
  editorial: "sequences/{sequenceId}/tracks/{trackId}/items",
  transform:
    "sequences/{sequenceId}/tracks/{trackId}/items/{targetId}/transform",
  transition: "sequences/{sequenceId}/tracks/{trackId}/items/{targetId}",
  effects: "effects/{effectId}",
  color: "effects/color/{targetId}",
  audio: "audio/{targetId}",
  captions: "sequences/{sequenceId}/captions",
  markers: "sequences/{sequenceId}/markers",
  analysis: "analyses/{targetId}",
  semantic: "project/derived-semantic-state",
  render: "jobs/{jobId}",
  interchange: "project/interchange",
};

function conflictSets(
  family: string,
  name: string,
): Pick<OperationDescriptor, "readSet" | "writeSet" | "expectedWarnings"> {
  const resource = resourceTemplates[family] ?? "project";
  const readOnly =
    name.endsWith(".detect") ||
    name.endsWith(".search") ||
    name.startsWith("preview.") ||
    name === "render.start" ||
    name.startsWith("semantic.find_");
  const destructive =
    name.includes("remove") ||
    name.includes("delete") ||
    name.includes("extract") ||
    name.includes("overwrite") ||
    name.includes("flatten");
  return {
    readSet: ["project.revision", resource],
    writeSet: readOnly ? [] : [resource],
    expectedWarnings: destructive
      ? ["Operation may remove or replace existing timeline state"]
      : [],
  };
}

export const operationCatalog: OperationDescriptor[] = Object.entries(
  operationFamilies,
).flatMap(([family, names]) =>
  names.map((name) => ({
    name,
    family,
    description: `FrameOS operation: ${humanize(name)}.`,
    maturity: implementedOperations.has(name)
      ? "implemented"
      : implementedServiceOperations.has(name)
        ? "service"
        : "contract",
    reversible: !name.endsWith(".detect") && !name.startsWith("render."),
    requiredCapabilities:
      name === "asset.proxy.create"
        ? ["asset.proxy.create"]
        : name === "asset.thumbnail.create"
          ? ["asset.thumbnail.create"]
          : name === "preview.waveform"
            ? ["preview.waveform"]
            : name.startsWith("render.") || name.startsWith("preview.")
              ? ["engine.mlt"]
              : [],
    ...conflictSets(family, name),
  })),
);

export function findOperation(name: string): OperationDescriptor | undefined {
  return operationCatalog.find((operation) => operation.name === name);
}
